production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
      
development:
  sessions:
    default:
      database: umlfiddle_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  sessions:
    default:
      database: umlfiddle_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
